/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author usuario
 */
public class VistaInicio extends javax.swing.JPanel {

    /**
     * Creates new form VistaInicio
     */
    public VistaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        maestrosButton = new javax.swing.JButton();
        ventasButton = new javax.swing.JButton();
        comprasButton = new javax.swing.JButton();
        informesButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        titleLabel.setText("DREAM GIFTS");
        titleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        titleLabel.setFocusable(false);
        jPanel1.add(titleLabel);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        maestrosButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maestrosButton.setText("Maestros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        jPanel2.add(maestrosButton, gridBagConstraints);

        ventasButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ventasButton.setText("Ventas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        jPanel2.add(ventasButton, gridBagConstraints);

        comprasButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comprasButton.setText("Compras");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        jPanel2.add(comprasButton, gridBagConstraints);

        informesButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        informesButton.setText("Informes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        jPanel2.add(informesButton, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton comprasButton;
    public javax.swing.JButton informesButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton maestrosButton;
    private javax.swing.JLabel titleLabel;
    public javax.swing.JButton ventasButton;
    // End of variables declaration//GEN-END:variables
}
